create extension if not exists "pgcrypto";

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text default '',
    education_stage text default 'high-school' check (education_stage in ('elementary', 'high-school', 'higher-studies')),
    preferred_study_duration integer default 45 check (preferred_study_duration between 15 and 180),
    timezone text default 'Asia/Kolkata',
    notifications_enabled boolean default true,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.subjects (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    accent_color text default '#8FB7A5',
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    unique (user_id, name)
);

create table if not exists public.study_plans (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    subject_id bigint references public.subjects(id) on delete set null,
    title text not null,
    description text default '',
    target_date date,
    estimated_effort_hours integer default 2 check (estimated_effort_hours > 0),
    priority text default 'medium' check (priority in ('low', 'medium', 'high')),
    status text default 'planned' check (status in ('planned', 'active', 'completed', 'archived')),
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.study_sessions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    plan_id bigint references public.study_plans(id) on delete set null,
    subject_id bigint references public.subjects(id) on delete set null,
    title text not null,
    scheduled_start timestamptz,
    scheduled_end timestamptz,
    actual_duration_minutes integer default 0 check (actual_duration_minutes >= 0),
    status text default 'planned' check (status in ('planned', 'completed', 'skipped', 'cancelled')),
    timer_mode text default 'pomodoro' check (timer_mode in ('pomodoro', 'custom', 'stopwatch')),
    focus_minutes integer default 25 check (focus_minutes > 0),
    break_minutes integer default 5 check (break_minutes >= 0),
    completed_at timestamptz,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    check (scheduled_end is null or scheduled_start is null or scheduled_end > scheduled_start)
);

create table if not exists public.timetable_entries (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    subject_id bigint references public.subjects(id) on delete set null,
    title text not null,
    day_of_week integer not null check (day_of_week between 0 and 6),
    entry_type text default 'study' check (entry_type in ('study', 'class', 'break')),
    start_time time not null,
    end_time time not null,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    check (end_time > start_time)
);

create table if not exists public.mood_entries (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    level integer not null check (level between 1 and 5),
    note text default '',
    logged_for date not null,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    unique (user_id, logged_for)
);

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.study_plans enable row level security;
alter table public.study_sessions enable row level security;
alter table public.timetable_entries enable row level security;
alter table public.mood_entries enable row level security;

drop trigger if exists set_profiles_updated_at on public.profiles;
drop trigger if exists set_subjects_updated_at on public.subjects;
drop trigger if exists set_study_plans_updated_at on public.study_plans;
drop trigger if exists set_study_sessions_updated_at on public.study_sessions;
drop trigger if exists set_timetable_entries_updated_at on public.timetable_entries;
drop trigger if exists set_mood_entries_updated_at on public.mood_entries;

create trigger set_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger set_subjects_updated_at before update on public.subjects for each row execute function public.set_updated_at();
create trigger set_study_plans_updated_at before update on public.study_plans for each row execute function public.set_updated_at();
create trigger set_study_sessions_updated_at before update on public.study_sessions for each row execute function public.set_updated_at();
create trigger set_timetable_entries_updated_at before update on public.timetable_entries for each row execute function public.set_updated_at();
create trigger set_mood_entries_updated_at before update on public.mood_entries for each row execute function public.set_updated_at();

drop policy if exists "profiles own rows" on public.profiles;
drop policy if exists "subjects own rows" on public.subjects;
drop policy if exists "plans own rows" on public.study_plans;
drop policy if exists "sessions own rows" on public.study_sessions;
drop policy if exists "timetable own rows" on public.timetable_entries;
drop policy if exists "moods own rows" on public.mood_entries;

create policy "profiles own rows" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "subjects own rows" on public.subjects for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "plans own rows" on public.study_plans for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "sessions own rows" on public.study_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "timetable own rows" on public.timetable_entries for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "moods own rows" on public.mood_entries for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
